use serde::{Deserialize, Serialize};

/// Represents a request to the Claude Messages API.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ClaudeRequest {
    /// The model ID to use (e.g., "claude-3-5-sonnet-20240620").
    pub model: String,
    /// Maximum number of tokens to generate.
    pub max_tokens: usize,
    /// Optional configuration for the "extended thinking" beta feature.
    pub thinking: Option<ThinkingConfig>,
    /// The conversation history leading up to this request.
    pub messages: Vec<Message>,
    /// Optional system prompt to guide the model's behavior.
    pub system: Option<String>,
    /// Optional list of tool definitions available to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<serde_json::Value>>,
}

/// Configuration for Claude's internal reasoning (thinking) process.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ThinkingConfig {
    /// The mode of thinking ("enabled" or "adaptive").
    pub r#type: String,
    /// Maximum number of tokens allocated to the thinking process.
    pub budget_tokens: usize,
}

/// A single exchange in the conversation history.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Message {
    /// The role of the speaker ("user" or "assistant").
    pub role: String,
    /// The various content segments within the message.
    pub content: Vec<ContentBlock>,
}

/// Represents different types of data blocks that can exist within a Message.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(tag = "type")]
pub enum ContentBlock {
    /// Standard text response.
    #[serde(rename = "text")]
    Text { text: String },
    /// An internal reasoning/thinking block (beta feature).
    #[serde(rename = "thinking")]
    Thinking { thinking: String, signature: String },
    /// A request from the model to use a specific tool.
    #[serde(rename = "tool_use")]
    ToolUse { id: String, name: String, input: serde_json::Value },
    /// The output/result from a executed tool.
    #[serde(rename = "tool_result")]
    ToolResult { tool_use_id: String, content: String },
}

impl ContentBlock {
    pub fn as_text(&self) -> Option<&str> {
        match self {
            ContentBlock::Text { text } => Some(text),
            _ => None,
        }
    }
}

/// The response returned by the Claude Messages API.
#[derive(Debug, Deserialize)]
pub struct ClaudeResponse {
    /// Unique identifier for the response.
    pub id: String,
    /// Role of the responder (usually "assistant").
    pub role: String,
    /// The content blocks generated by the model.
    pub content: Vec<ContentBlock>,
    /// The reason why generation stopped (e.g., "end_turn", "tool_use").
    pub stop_reason: Option<String>,
    /// The sequence that triggered the stop.
    pub stop_sequence: Option<String>,
    /// Token usage statistics for this request.
    pub usage: Usage,
}

#[derive(Debug, Deserialize)]
pub struct Usage {
    pub input_tokens: usize,
    pub output_tokens: usize,
}
